AdobeXMPCore Namespace Reference
AdobeXMPCore Namespace Reference
Classes
class IArrayNode_v1
Version1 of the interface that represents an Array Node of XMP DOM.
class IClientDOMParser_v1
Version 1 of the interface that supports parsing by the client supplied parser of the XMP Data Model.
class IClientDOMSerializer_v1
Version 1 of the interface that supports serializing by the client supplied serializer of the XMP Data Model.
class ICompositeNode_v1
Version1 of the interface that serves as a base interface to all composite types of nodes in the XMP DOM (like Arrays and Structures).
class ICoreConfigurationManager_v1
Version1 of the interface that represents configuration settings controllable by the client.
class ICoreObjectFactory_v1
Version1 of a interface that represents a factory to create various artifacts of XMP DOM like array, structure, path etc.
class IDOMImplementationRegistry_v1
Version1 of the interface that serves as a database/registry of all the parsers and serializers available with the XMPCore library.
class IDOMParser_v1
Version 1 of the interface that supports parsing of the XMP Data Model.
class IDOMSerializer_v1
Version1 of the interface that represents an object that can serialize an XMP Data Model to a buffer. Provides the functions to serialize the XMP Data Model.
class IMetadata_v1
Version1 of the interface that represents the whole xmp metadata for an asset.
class INameSpacePrefixMap_v1
Version1 of the interface that represents map where each entry consists of prefix string as the key and corresponding nameSpace string as its value.
class INode_v1
Version1 of the interface that serves as a base interface to all types of nodes in the XMP DOM.
class INodeIterator_v1
Interface that represents an iterator over the mutable children of a XMP DOM Node.
class IPath_v1
Version1 of the interface that provides an easy iterative description of a specific path into the XMP tree.
class IPathSegment_v1
Version1 of the interface that represents one segment in a path to a node into the XMP tree.
class ISimpleNode_v1
Version1 of the interface that represents a Simple Property Node of XMP DOM.
class IStructureNode_v1
Version1 of the interface that represents a structure Node of XMP DOM.
Typedefs
typedef INameSpacePrefixMap_v1 INameSpacePrefixMap_base
typedef INameSpacePrefixMap_v1 * pINameSpacePrefixMap_base
typedef const INameSpacePrefixMap_v1 * pcINameSpacePrefixMap_base
typedef INameSpacePrefixMap * pINameSpacePrefixMap
typedef const INameSpacePrefixMap * pcINameSpacePrefixMap
typedef shared_ptr< INameSpacePrefixMap > spINameSpacePrefixMap
typedef shared_ptr< const INameSpacePrefixMap > spcINameSpacePrefixMap
typedef IPathSegment_v1 IPathSegment_base
typedef IPathSegment_v1 * pIPathSegment_base
typedef const IPathSegment_v1 * pcIPathSegment_base
typedef IPathSegment * pIPathSegment
typedef const IPathSegment * pcIPathSegment
typedef shared_ptr< IPathSegment > spIPathSegment
typedef shared_ptr< const IPathSegment > spcIPathSegment
typedef IPath_v1 IPath_base
typedef IPath_v1 * pIPath_base
typedef const IPath_v1 * pcIPath_base
typedef IPath * pIPath
typedef const IPath * pcIPath
typedef shared_ptr< IPath > spIPath
typedef shared_ptr< const IPath > spcIPath
typedef INode_v1 INode_base
typedef INode_v1 * pINode_base
typedef const INode_v1 * pcINode_base
typedef INode * pINode
typedef const INode * pcINode
typedef shared_ptr< INode > spINode
typedef shared_ptr< const INode > spcINode
typedef ISimpleNode_v1 ISimpleNode_base
typedef ISimpleNode_v1 * pISimpleNode_base
typedef const ISimpleNode_v1 * pcISimpleNode_base
typedef ISimpleNode * pISimpleNode
typedef const ISimpleNode * pcISimpleNode
typedef shared_ptr< ISimpleNode > spISimpleNode
typedef shared_ptr< const ISimpleNode > spcISimpleNode
typedef ICompositeNode_v1 ICompositeNode_base
typedef ICompositeNode_v1 * pICompositeNode_base
typedef const ICompositeNode_v1 * pcICompositeNode_base
typedef ICompositeNode * pICompositeNode
typedef const ICompositeNode * pcICompositeNode
typedef shared_ptr< ICompositeNode > spICompositeNode
typedef shared_ptr< const ICompositeNode > spcICompositeNode
typedef IStructureNode_v1 IStructureNode_base
typedef IStructureNode_v1 * pIStructureNode_base
typedef const IStructureNode_v1 * pcIStructureNode_base
typedef IStructureNode * pIStructureNode
typedef const IStructureNode * pcIStructureNode
typedef shared_ptr< IStructureNode > spIStructureNode
typedef shared_ptr< const IStructureNode > spcIStructureNode
typedef IArrayNode_v1 IArrayNode_base
typedef IArrayNode_v1 * pIArrayNode_base
typedef const IArrayNode_v1 * pcIArrayNode_base
typedef IArrayNode * pIArrayNode
typedef const IArrayNode * pcIArrayNode
typedef shared_ptr< IArrayNode > spIArrayNode
typedef shared_ptr< const IArrayNode > spcIArrayNode
typedef INodeIterator_v1 INodeIterator_base
typedef INodeIterator_v1 * pINodeIterator_base
typedef const INodeIterator_v1 * pcINodeIterator_base
typedef INodeIterator * pINodeIterator
typedef const INodeIterator * pcINodeIterator
typedef shared_ptr< INodeIterator > spINodeIterator
typedef shared_ptr< const INodeIterator > spcINodeIterator
typedef IMetadata_v1 IMetadata_base
typedef IMetadata_v1 * pIMetadata_base
typedef const IMetadata_v1 * pcIMetadata_base
typedef IMetadata * pIMetadata
typedef const IMetadata * pcIMetadata
typedef shared_ptr< IMetadata > spIMetadata
typedef shared_ptr< const IMetadata > spcIMetadata
typedef IClientDOMParser_v1 IClientDOMParser_base
typedef IClientDOMParser_v1 * pIClientDOMParser_base
typedef const IClientDOMParser_v1 * pcIClientDOMParser_base
typedef IClientDOMParser * pIClientDOMParser
typedef const IClientDOMParser * pcIClientDOMParser
typedef IClientDOMSerializer_v1 IClientDOMSerializer_base
typedef IClientDOMSerializer_v1 * pIClientDOMSerializer_base
typedef const IClientDOMSerializer_v1 * pcIClientDOMSerializer_base
typedef IClientDOMSerializer * pIClientDOMSerializer
typedef const IClientDOMSerializer * pcIClientDOMSerializer
typedef IDOMParser_v1 IDOMParser_base
typedef IDOMParser_v1 * pIDOMParser_base
typedef const IDOMParser_v1 * pcIDOMParser_base
typedef IDOMParser * pIDOMParser
typedef const IDOMParser * pcIDOMParser
typedef shared_ptr< IDOMParser > spIDOMParser
typedef shared_ptr< const IDOMParser > spcIDOMParser
typedef IDOMSerializer_v1 IDOMSerializer_base
typedef IDOMSerializer_v1 * pIDOMSerializer_base
typedef const IDOMSerializer_v1 * pcIDOMSerializer_base
typedef IDOMSerializer * pIDOMSerializer
typedef const IDOMSerializer * pcIDOMSerializer
typedef shared_ptr< IDOMSerializer > spIDOMSerializer
typedef shared_ptr< const IDOMSerializer > spcIDOMSerializer
typedef IDOMImplementationRegistry_v1 IDOMImplementationRegistry_base
typedef IDOMImplementationRegistry_v1 * pIDOMImplementationRegistry_base
typedef const IDOMImplementationRegistry_v1 * pcIDOMImplementationRegistry_base
typedef IDOMImplementationRegistry * pIDOMImplementationRegistry
typedef const IDOMImplementationRegistry * pcIDOMImplementationRegistry
typedef shared_ptr< IDOMImplementationRegistry > spIDOMImplementationRegistry
typedef shared_ptr< const IDOMImplementationRegistry > spcIDOMImplementationRegistry
typedef ICoreObjectFactory_v1 ICoreObjectFactory_base
typedef ICoreObjectFactory_v1 * pICoreObjectFactory_base
typedef const ICoreObjectFactory_v1 * pcICoreObjectFactory_base
typedef ICoreObjectFactory * pICoreObjectFactory
typedef const ICoreObjectFactory * pcICoreObjectFactory
typedef ICoreConfigurationManager_v1 ICoreConfigurationManager_base
typedef ICoreConfigurationManager_v1 * pICoreConfigurationManager_base
typedef const ICoreConfigurationManager_v1 * pcICoreConfigurationManager_base
typedef ICoreConfigurationManager * pICoreConfigurationManager
typedef const ICoreConfigurationManager * pcICoreConfigurationManager
typedef shared_ptr< ICoreConfigurationManager > spICoreConfigurationManager
typedef shared_ptr< const ICoreConfigurationManager > spcICoreConfigurationManager
Enumerations
enum eDataModelErrorCode {
kDMECNone = 0, kDMECNameSpacePrefixMapEntryMissing = 1, kDMECDifferentNodeTypePresent = 2, kDMECNodeAlreadyAChild = 3,
kDMECNodeAlreadyExists = 4, kDMECNoSuchNodeExists = 5, kDMECArrayItemTypeDifferent = 6, kDMECInvalidPathSegment = 7,
kDMECBadSchema = 101, kDMECBadXPath = 102, kDMECBadOptions = 103, kDMECBadIterPosition = 104,
kDMECBadUnicode = 105, kDMECValidationError = 106, kDMECEmptyIterator = 107, kDMECMaxValue = kMaxEnumValue
}
enum eParserErrorCode {
kPECNone = 0, kPECBadXML = 1, kPECBadRDF = 2, kPECBadXMP = 3,
kPECInvalidContextNode = 4, kPECContextNodeIsNonComposite = 5, kPECContextNodeParentIsNonArray = 6, kPECMaxValue = kMaxEnumValue
}
Indicates various errors encountered during parsing.
enum eSerializerErrorCode { kSECNone = 0, kSECSizeExceed = 1, kSECUnRegisteredNameSpace = 2, kSECMaxValue = kMaxEnumValue }
Indicates various errors encountered during serialization.
Functions
typedef BASE_CLASS (INameSpacePrefixMap, INAMESPACEPREFIXMAP_VERSION) INameSpacePrefixMap
static const uint64 kINameSpacePrefixMapID (0x634e5350724d6170)
typedef BASE_CLASS (IPathSegment, IPATHSEGMENT_VERSION) IPathSegment
static const uint64 kIPathSegmentID (0x6350617468536567)
typedef BASE_CLASS (IPath, IPATH_VERSION) IPath
static const uint64 kIPathID (0x6350617468202020)
typedef BASE_CLASS (INode, INODE_VERSION) INode
static const uint64 kINodeID (0x634e6f6465202020)
typedef BASE_CLASS (ISimpleNode, ISIMPLENODE_VERSION) ISimpleNode
static const uint64 kISimpleNodeID (0x63536d6c4e6f6465)
typedef BASE_CLASS (ICompositeNode, ICOMPOSITENODE_VERSION) ICompositeNode
static const uint64 kICompositeNodeID (0x63436d704e6f6465)
typedef BASE_CLASS (IStructureNode, ISTRUCTURENODE_VERSION) IStructureNode
static const uint64 kIStructureNodeID (0x635374724e6f6465)
typedef BASE_CLASS (IArrayNode, IARRAYNODE_VERSION) IArrayNode
static const uint64 kIArrayNodeID (0x634172724e6f6465)
typedef BASE_CLASS (INodeIterator, INODEITERATOR_VERSION) INodeIterator
static const uint64 kINodeIteratorID (0x634e6f6465497420)
typedef BASE_CLASS (IMetadata, IMETADATA_VERSION) IMetadata
static const uint64 kIMetadataID (0x634d657461646174)
typedef BASE_CLASS (IClientDOMParser, ICLIENTDOMPARSER_VERSION) IClientDOMParser
typedef BASE_CLASS (IClientDOMSerializer, ICLIENTDOMSERIALIZER_VERSION) IClientDOMSerializer
typedef BASE_CLASS (IDOMParser, IDOMPARSER_VERSION) IDOMParser
static const uint64 kIDOMParserID (0x63444f4d50727372)
typedef BASE_CLASS (IDOMSerializer, IDOMSERIALIZER_VERSION) IDOMSerializer
static const uint64 kIDOMSerializerID (0x63444f4d53726c7a)
typedef BASE_CLASS (IDOMImplementationRegistry, IDOMIMPLEMENTATIONREGISTRY_VERSION) IDOMImplementationRegistry
static const uint64 kIDOMImplementationRegistryID (0x63444f4d52677374)
typedef BASE_CLASS (ICoreObjectFactory, ICOREOBJECTFACTORY_VERSION) ICoreObjectFactory
static const uint64 kICoreObjectFactoryID (0x634f626a46616374)
typedef BASE_CLASS (ICoreConfigurationManager, ICORECONFIGURATIONMANAGER_VERSION) ICoreConfigurationManager
static const uint64 kICoreConfigurationManagerID (0x63436f6e664d6772)
Typedef Documentation
typedef IArrayNode_v1 AdobeXMPCore::IArrayNode_base
Definition at line 106 of file XMPCoreFwdDeclarations.h.
typedef IClientDOMParser_v1 AdobeXMPCore::IClientDOMParser_base
Definition at line 142 of file XMPCoreFwdDeclarations.h.
typedef IClientDOMSerializer_v1 AdobeXMPCore::IClientDOMSerializer_base
Definition at line 151 of file XMPCoreFwdDeclarations.h.
typedef ICompositeNode_v1 AdobeXMPCore::ICompositeNode_base
Definition at line 82 of file XMPCoreFwdDeclarations.h.
typedef ICoreConfigurationManager_v1 AdobeXMPCore::ICoreConfigurationManager_base
Definition at line 206 of file XMPCoreFwdDeclarations.h.
typedef ICoreObjectFactory_v1 AdobeXMPCore::ICoreObjectFactory_base
Definition at line 196 of file XMPCoreFwdDeclarations.h.
typedef IDOMImplementationRegistry_v1 AdobeXMPCore::IDOMImplementationRegistry_base
Definition at line 184 of file XMPCoreFwdDeclarations.h.
typedef IDOMParser_v1 AdobeXMPCore::IDOMParser_base
Definition at line 160 of file XMPCoreFwdDeclarations.h.
typedef IDOMSerializer_v1 AdobeXMPCore::IDOMSerializer_base
Definition at line 172 of file XMPCoreFwdDeclarations.h.
typedef IMetadata_v1 AdobeXMPCore::IMetadata_base
Definition at line 130 of file XMPCoreFwdDeclarations.h.
typedef INameSpacePrefixMap_v1 AdobeXMPCore::INameSpacePrefixMap_base
Definition at line 22 of file XMPCoreFwdDeclarations.h.
typedef INode_v1 AdobeXMPCore::INode_base
Definition at line 58 of file XMPCoreFwdDeclarations.h.
typedef INodeIterator_v1 AdobeXMPCore::INodeIterator_base
Definition at line 118 of file XMPCoreFwdDeclarations.h.
typedef IPath_v1 AdobeXMPCore::IPath_base
Definition at line 46 of file XMPCoreFwdDeclarations.h.
typedef IPathSegment_v1 AdobeXMPCore::IPathSegment_base
Definition at line 34 of file XMPCoreFwdDeclarations.h.
typedef ISimpleNode_v1 AdobeXMPCore::ISimpleNode_base
Definition at line 70 of file XMPCoreFwdDeclarations.h.
typedef IStructureNode_v1 AdobeXMPCore::IStructureNode_base
Definition at line 94 of file XMPCoreFwdDeclarations.h.
typedef const IArrayNode* AdobeXMPCore::pcIArrayNode
Definition at line 112 of file XMPCoreFwdDeclarations.h.
typedef const IArrayNode_v1* AdobeXMPCore::pcIArrayNode_base
Definition at line 109 of file XMPCoreFwdDeclarations.h.
typedef const IClientDOMParser* AdobeXMPCore::pcIClientDOMParser
Definition at line 148 of file XMPCoreFwdDeclarations.h.
typedef const IClientDOMParser_v1* AdobeXMPCore::pcIClientDOMParser_base
Definition at line 145 of file XMPCoreFwdDeclarations.h.
typedef const IClientDOMSerializer* AdobeXMPCore::pcIClientDOMSerializer
Definition at line 157 of file XMPCoreFwdDeclarations.h.
typedef const IClientDOMSerializer_v1* AdobeXMPCore::pcIClientDOMSerializer_base
Definition at line 154 of file XMPCoreFwdDeclarations.h.
typedef const ICompositeNode* AdobeXMPCore::pcICompositeNode
Definition at line 88 of file XMPCoreFwdDeclarations.h.
typedef const ICompositeNode_v1* AdobeXMPCore::pcICompositeNode_base
Definition at line 85 of file XMPCoreFwdDeclarations.h.
typedef const ICoreConfigurationManager* AdobeXMPCore::pcICoreConfigurationManager
Definition at line 212 of file XMPCoreFwdDeclarations.h.
typedef const ICoreConfigurationManager_v1* AdobeXMPCore::pcICoreConfigurationManager_base
Definition at line 209 of file XMPCoreFwdDeclarations.h.
typedef const ICoreObjectFactory* AdobeXMPCore::pcICoreObjectFactory
Definition at line 202 of file XMPCoreFwdDeclarations.h.
typedef const ICoreObjectFactory_v1* AdobeXMPCore::pcICoreObjectFactory_base
Definition at line 199 of file XMPCoreFwdDeclarations.h.
typedef const IDOMImplementationRegistry* AdobeXMPCore::pcIDOMImplementationRegistry
Definition at line 190 of file XMPCoreFwdDeclarations.h.
typedef const IDOMImplementationRegistry_v1* AdobeXMPCore::pcIDOMImplementationRegistry_base
Definition at line 187 of file XMPCoreFwdDeclarations.h.
typedef const IDOMParser* AdobeXMPCore::pcIDOMParser
Definition at line 166 of file XMPCoreFwdDeclarations.h.
typedef const IDOMParser_v1* AdobeXMPCore::pcIDOMParser_base
Definition at line 163 of file XMPCoreFwdDeclarations.h.
typedef const IDOMSerializer* AdobeXMPCore::pcIDOMSerializer
Definition at line 178 of file XMPCoreFwdDeclarations.h.
typedef const IDOMSerializer_v1* AdobeXMPCore::pcIDOMSerializer_base
Definition at line 175 of file XMPCoreFwdDeclarations.h.
typedef const IMetadata* AdobeXMPCore::pcIMetadata
Definition at line 136 of file XMPCoreFwdDeclarations.h.
typedef const IMetadata_v1* AdobeXMPCore::pcIMetadata_base
Definition at line 133 of file XMPCoreFwdDeclarations.h.
typedef const INameSpacePrefixMap* AdobeXMPCore::pcINameSpacePrefixMap
Definition at line 28 of file XMPCoreFwdDeclarations.h.
typedef const INameSpacePrefixMap_v1* AdobeXMPCore::pcINameSpacePrefixMap_base
Definition at line 25 of file XMPCoreFwdDeclarations.h.
typedef const INode* AdobeXMPCore::pcINode
Definition at line 64 of file XMPCoreFwdDeclarations.h.
typedef const INode_v1* AdobeXMPCore::pcINode_base
Definition at line 61 of file XMPCoreFwdDeclarations.h.
typedef const INodeIterator* AdobeXMPCore::pcINodeIterator
Definition at line 124 of file XMPCoreFwdDeclarations.h.
typedef const INodeIterator_v1* AdobeXMPCore::pcINodeIterator_base
Definition at line 121 of file XMPCoreFwdDeclarations.h.
typedef const IPath* AdobeXMPCore::pcIPath
Definition at line 52 of file XMPCoreFwdDeclarations.h.
typedef const IPath_v1* AdobeXMPCore::pcIPath_base
Definition at line 49 of file XMPCoreFwdDeclarations.h.
typedef const IPathSegment* AdobeXMPCore::pcIPathSegment
Definition at line 40 of file XMPCoreFwdDeclarations.h.
typedef const IPathSegment_v1* AdobeXMPCore::pcIPathSegment_base
Definition at line 37 of file XMPCoreFwdDeclarations.h.
typedef const ISimpleNode* AdobeXMPCore::pcISimpleNode
Definition at line 76 of file XMPCoreFwdDeclarations.h.
typedef const ISimpleNode_v1* AdobeXMPCore::pcISimpleNode_base
Definition at line 73 of file XMPCoreFwdDeclarations.h.
typedef const IStructureNode* AdobeXMPCore::pcIStructureNode
Definition at line 100 of file XMPCoreFwdDeclarations.h.
typedef const IStructureNode_v1* AdobeXMPCore::pcIStructureNode_base
Definition at line 97 of file XMPCoreFwdDeclarations.h.
typedef IArrayNode* AdobeXMPCore::pIArrayNode
Definition at line 111 of file XMPCoreFwdDeclarations.h.
typedef IArrayNode_v1* AdobeXMPCore::pIArrayNode_base
Definition at line 108 of file XMPCoreFwdDeclarations.h.
typedef IClientDOMParser* AdobeXMPCore::pIClientDOMParser
Definition at line 147 of file XMPCoreFwdDeclarations.h.
typedef IClientDOMParser_v1* AdobeXMPCore::pIClientDOMParser_base
Definition at line 144 of file XMPCoreFwdDeclarations.h.
typedef IClientDOMSerializer* AdobeXMPCore::pIClientDOMSerializer
Definition at line 156 of file XMPCoreFwdDeclarations.h.
typedef IClientDOMSerializer_v1* AdobeXMPCore::pIClientDOMSerializer_base
Definition at line 153 of file XMPCoreFwdDeclarations.h.
typedef ICompositeNode* AdobeXMPCore::pICompositeNode
Definition at line 87 of file XMPCoreFwdDeclarations.h.
typedef ICompositeNode_v1* AdobeXMPCore::pICompositeNode_base
Definition at line 84 of file XMPCoreFwdDeclarations.h.
typedef ICoreConfigurationManager* AdobeXMPCore::pICoreConfigurationManager
Definition at line 211 of file XMPCoreFwdDeclarations.h.
typedef ICoreConfigurationManager_v1* AdobeXMPCore::pICoreConfigurationManager_base
Definition at line 208 of file XMPCoreFwdDeclarations.h.
typedef ICoreObjectFactory* AdobeXMPCore::pICoreObjectFactory
Definition at line 201 of file XMPCoreFwdDeclarations.h.
typedef ICoreObjectFactory_v1* AdobeXMPCore::pICoreObjectFactory_base
Definition at line 198 of file XMPCoreFwdDeclarations.h.
typedef IDOMImplementationRegistry* AdobeXMPCore::pIDOMImplementationRegistry
Definition at line 189 of file XMPCoreFwdDeclarations.h.
typedef IDOMImplementationRegistry_v1* AdobeXMPCore::pIDOMImplementationRegistry_base
Definition at line 186 of file XMPCoreFwdDeclarations.h.
typedef IDOMParser* AdobeXMPCore::pIDOMParser
Definition at line 165 of file XMPCoreFwdDeclarations.h.
typedef IDOMParser_v1* AdobeXMPCore::pIDOMParser_base
Definition at line 162 of file XMPCoreFwdDeclarations.h.
typedef IDOMSerializer* AdobeXMPCore::pIDOMSerializer
Definition at line 177 of file XMPCoreFwdDeclarations.h.
typedef IDOMSerializer_v1* AdobeXMPCore::pIDOMSerializer_base
Definition at line 174 of file XMPCoreFwdDeclarations.h.
typedef IMetadata* AdobeXMPCore::pIMetadata
Definition at line 135 of file XMPCoreFwdDeclarations.h.
typedef IMetadata_v1* AdobeXMPCore::pIMetadata_base
Definition at line 132 of file XMPCoreFwdDeclarations.h.
typedef INameSpacePrefixMap* AdobeXMPCore::pINameSpacePrefixMap
Definition at line 27 of file XMPCoreFwdDeclarations.h.
typedef INameSpacePrefixMap_v1* AdobeXMPCore::pINameSpacePrefixMap_base
Definition at line 24 of file XMPCoreFwdDeclarations.h.
typedef INode* AdobeXMPCore::pINode
Definition at line 63 of file XMPCoreFwdDeclarations.h.
typedef INode_v1* AdobeXMPCore::pINode_base
Definition at line 60 of file XMPCoreFwdDeclarations.h.
typedef INodeIterator* AdobeXMPCore::pINodeIterator
Definition at line 123 of file XMPCoreFwdDeclarations.h.
typedef INodeIterator_v1* AdobeXMPCore::pINodeIterator_base
Definition at line 120 of file XMPCoreFwdDeclarations.h.
typedef IPath* AdobeXMPCore::pIPath
Definition at line 51 of file XMPCoreFwdDeclarations.h.
typedef IPath_v1* AdobeXMPCore::pIPath_base
Definition at line 48 of file XMPCoreFwdDeclarations.h.
typedef IPathSegment* AdobeXMPCore::pIPathSegment
Definition at line 39 of file XMPCoreFwdDeclarations.h.
typedef IPathSegment_v1* AdobeXMPCore::pIPathSegment_base
Definition at line 36 of file XMPCoreFwdDeclarations.h.
typedef ISimpleNode* AdobeXMPCore::pISimpleNode
Definition at line 75 of file XMPCoreFwdDeclarations.h.
typedef ISimpleNode_v1* AdobeXMPCore::pISimpleNode_base
Definition at line 72 of file XMPCoreFwdDeclarations.h.
typedef IStructureNode* AdobeXMPCore::pIStructureNode
Definition at line 99 of file XMPCoreFwdDeclarations.h.
typedef IStructureNode_v1* AdobeXMPCore::pIStructureNode_base
Definition at line 96 of file XMPCoreFwdDeclarations.h.
typedef shared_ptr< const IArrayNode > AdobeXMPCore::spcIArrayNode
Definition at line 114 of file XMPCoreFwdDeclarations.h.
typedef shared_ptr< const ICompositeNode > AdobeXMPCore::spcICompositeNode
Definition at line 90 of file XMPCoreFwdDeclarations.h.
typedef shared_ptr< const ICoreConfigurationManager > AdobeXMPCore::spcICoreConfigurationManager
Definition at line 214 of file XMPCoreFwdDeclarations.h.
typedef shared_ptr< const IDOMImplementationRegistry > AdobeXMPCore::spcIDOMImplementationRegistry
Definition at line 192 of file XMPCoreFwdDeclarations.h.
typedef shared_ptr< const IDOMParser > AdobeXMPCore::spcIDOMParser
Definition at line 168 of file XMPCoreFwdDeclarations.h.
typedef shared_ptr< const IDOMSerializer > AdobeXMPCore::spcIDOMSerializer
Definition at line 180 of file XMPCoreFwdDeclarations.h.
typedef shared_ptr< const IMetadata > AdobeXMPCore::spcIMetadata
Definition at line 138 of file XMPCoreFwdDeclarations.h.
typedef shared_ptr< const INameSpacePrefixMap > AdobeXMPCore::spcINameSpacePrefixMap
Definition at line 30 of file XMPCoreFwdDeclarations.h.
typedef shared_ptr< const INode > AdobeXMPCore::spcINode
Definition at line 66 of file XMPCoreFwdDeclarations.h.
typedef shared_ptr< const INodeIterator > AdobeXMPCore::spcINodeIterator
Definition at line 126 of file XMPCoreFwdDeclarations.h.
typedef shared_ptr< const IPath > AdobeXMPCore::spcIPath
Definition at line 54 of file XMPCoreFwdDeclarations.h.
typedef shared_ptr< const IPathSegment > AdobeXMPCore::spcIPathSegment
Definition at line 42 of file XMPCoreFwdDeclarations.h.
typedef shared_ptr< const ISimpleNode > AdobeXMPCore::spcISimpleNode
Definition at line 78 of file XMPCoreFwdDeclarations.h.
typedef shared_ptr< const IStructureNode > AdobeXMPCore::spcIStructureNode
Definition at line 102 of file XMPCoreFwdDeclarations.h.
typedef shared_ptr< IArrayNode > AdobeXMPCore::spIArrayNode
Definition at line 113 of file XMPCoreFwdDeclarations.h.
typedef shared_ptr< ICompositeNode > AdobeXMPCore::spICompositeNode
Definition at line 89 of file XMPCoreFwdDeclarations.h.
typedef shared_ptr< ICoreConfigurationManager > AdobeXMPCore::spICoreConfigurationManager
Definition at line 213 of file XMPCoreFwdDeclarations.h.
typedef shared_ptr< IDOMImplementationRegistry > AdobeXMPCore::spIDOMImplementationRegistry
Definition at line 191 of file XMPCoreFwdDeclarations.h.
typedef shared_ptr< IDOMParser > AdobeXMPCore::spIDOMParser
Definition at line 167 of file XMPCoreFwdDeclarations.h.
typedef shared_ptr< IDOMSerializer > AdobeXMPCore::spIDOMSerializer
Definition at line 179 of file XMPCoreFwdDeclarations.h.
typedef shared_ptr< IMetadata > AdobeXMPCore::spIMetadata
Definition at line 137 of file XMPCoreFwdDeclarations.h.
typedef shared_ptr< INameSpacePrefixMap > AdobeXMPCore::spINameSpacePrefixMap
Definition at line 29 of file XMPCoreFwdDeclarations.h.
typedef shared_ptr< INode > AdobeXMPCore::spINode
Definition at line 65 of file XMPCoreFwdDeclarations.h.
typedef shared_ptr< INodeIterator > AdobeXMPCore::spINodeIterator
Definition at line 125 of file XMPCoreFwdDeclarations.h.
typedef shared_ptr< IPath > AdobeXMPCore::spIPath
Definition at line 53 of file XMPCoreFwdDeclarations.h.
typedef shared_ptr< IPathSegment > AdobeXMPCore::spIPathSegment
Definition at line 41 of file XMPCoreFwdDeclarations.h.
typedef shared_ptr< ISimpleNode > AdobeXMPCore::spISimpleNode
Definition at line 77 of file XMPCoreFwdDeclarations.h.
typedef shared_ptr< IStructureNode > AdobeXMPCore::spIStructureNode
Definition at line 101 of file XMPCoreFwdDeclarations.h.
Enumeration Type Documentation
enum AdobeXMPCore::eDataModelErrorCode
Enumerator
kDMECNone
Indicates no error.
kDMECNameSpacePrefixMapEntryMissing
Indicates that IXMPNameSpacePrefixMap has an entry missing.
kDMECDifferentNodeTypePresent
Indicates that a different type of node is present than one user is expecting.
kDMECNodeAlreadyAChild
Indicates that node is already a child of another parent.
kDMECNodeAlreadyExists
Indicates a node with the same qualified name or index already exists.
kDMECNoSuchNodeExists
Indicates no such node exists.
kDMECArrayItemTypeDifferent
Indicates current array element type is not same as that of other child items.
kDMECInvalidPathSegment
Indicates invalid path segment inside a path.
kDMECBadSchema
Indicates Bad schema parameter.
kDMECBadXPath
Indicates Bad XPath parameter.
kDMECBadOptions
Indicates Bad options parameter.
kDMECBadIterPosition
Indicates Bad iteration position.
kDMECBadUnicode
Indicates Unicode error.
kDMECValidationError
Indicates XMP format error.
kDMECEmptyIterator
Indicates Empty iterator.
kDMECMaxValue
Maximum value this enum can hold, should be treated as invalid value.
Definition at line 18 of file XMPCoreErrorCodes.h.
                      {
                 kDMECNone                                                                       = 0,
                 kDMECNameSpacePrefixMapEntryMissing                     = 1,
                 kDMECDifferentNodeTypePresent                           = 2,
                 kDMECNodeAlreadyAChild                                          = 3,
                 kDMECNodeAlreadyExists                                          = 4,
                 kDMECNoSuchNodeExists                                           = 5,
                 kDMECArrayItemTypeDifferent                                     = 6,
                 kDMECInvalidPathSegment                                         = 7,
                 kDMECBadSchema                                                          = 101,
                 kDMECBadXPath                                                           = 102,
                 kDMECBadOptions                                                         = 103,
                 kDMECBadIterPosition                                            = 104,
                 kDMECBadUnicode                                                         = 105,
                 kDMECValidationError                                            = 106,
                 kDMECEmptyIterator                                                      = 107,
                 kDMECMaxValue                                                           = kMaxEnumValue
         } eDataModelErrorCode;
enum AdobeXMPCore::eParserErrorCode
Indicates various errors encountered during parsing.
Enumerator
kPECNone
Indicates no error.
kPECBadXML
Indicates XML parsing error.
kPECBadRDF
RDF format error.
kPECBadXMP
XMP format error.
kPECInvalidContextNode
Context Node is invalid.
kPECContextNodeIsNonComposite
Context Node is not a composite node.
kPECContextNodeParentIsNonArray
Parent of Context Node is not an array node.
kPECMaxValue
Maximum value this enum can hold, should be treated as invalid value.
Definition at line 71 of file XMPCoreErrorCodes.h.
                      {
                 kPECNone                                                                        = 0,
                 kPECBadXML                                                                      = 1,
                 kPECBadRDF                                                                      = 2,
                 kPECBadXMP                                                                      = 3,
                 kPECInvalidContextNode                                          = 4,
                 kPECContextNodeIsNonComposite                           = 5,
                 kPECContextNodeParentIsNonArray                         = 6,
                 kPECMaxValue                                                            = kMaxEnumValue
         } eParserErrorCode;
enum AdobeXMPCore::eSerializerErrorCode
Indicates various errors encountered during serialization.
Enumerator
kSECNone
Indicates no error.
kSECSizeExceed
Indicates serialization failed to achieve size requirement.
kSECUnRegisteredNameSpace
Indicates un registered namespace encountered during serialization.
kSECMaxValue
Maximum value this enum can hold, should be treated as invalid value.
Definition at line 100 of file XMPCoreErrorCodes.h.
                      {
                 kSECNone                                                                        = 0,
                 kSECSizeExceed                                                          = 1,
                 kSECUnRegisteredNameSpace                                       = 2,
                 kSECMaxValue                                                            = kMaxEnumValue
         } eSerializerErrorCode;
Function Documentation
typedef AdobeXMPCore::BASE_CLASS (INameSpacePrefixMap , INAMESPACEPREFIXMAP_VERSION)
typedef AdobeXMPCore::BASE_CLASS (IPathSegment , IPATHSEGMENT_VERSION)
typedef AdobeXMPCore::BASE_CLASS (IPath , IPATH_VERSION)
typedef AdobeXMPCore::BASE_CLASS (INode , INODE_VERSION)
typedef AdobeXMPCore::BASE_CLASS (ISimpleNode , ISIMPLENODE_VERSION)
typedef AdobeXMPCore::BASE_CLASS (ICompositeNode , ICOMPOSITENODE_VERSION)
typedef AdobeXMPCore::BASE_CLASS (IStructureNode , ISTRUCTURENODE_VERSION)
typedef AdobeXMPCore::BASE_CLASS (IArrayNode , IARRAYNODE_VERSION)
typedef AdobeXMPCore::BASE_CLASS (INodeIterator , INODEITERATOR_VERSION)
typedef AdobeXMPCore::BASE_CLASS (IMetadata , IMETADATA_VERSION)
typedef AdobeXMPCore::BASE_CLASS (IClientDOMParser , ICLIENTDOMPARSER_VERSION)
typedef AdobeXMPCore::BASE_CLASS (IClientDOMSerializer , ICLIENTDOMSERIALIZER_VERSION)
typedef AdobeXMPCore::BASE_CLASS (IDOMParser , IDOMPARSER_VERSION)
typedef AdobeXMPCore::BASE_CLASS (IDOMSerializer , IDOMSERIALIZER_VERSION)
typedef AdobeXMPCore::BASE_CLASS (IDOMImplementationRegistry , IDOMIMPLEMENTATIONREGISTRY_VERSION)
typedef AdobeXMPCore::BASE_CLASS (ICoreObjectFactory , ICOREOBJECTFACTORY_VERSION)
typedef AdobeXMPCore::BASE_CLASS (ICoreConfigurationManager , ICORECONFIGURATIONMANAGER_VERSION)
static const uint64 AdobeXMPCore::kIArrayNodeID (0x634172724e6f6465) static
Referenced by AdobeXMPCore::IArrayNode_v1::GetArrayNodeAtIndex().
static const uint64 AdobeXMPCore::kICompositeNodeID (0x63436d704e6f6465) static
Referenced by AdobeXMPCore::ICompositeNode_v1::GetArrayNodeAtPath().
static const uint64 AdobeXMPCore::kICoreConfigurationManagerID (0x63436f6e664d6772) static
static const uint64 AdobeXMPCore::kICoreObjectFactoryID (0x634f626a46616374) static
static const uint64 AdobeXMPCore::kIDOMImplementationRegistryID (0x63444f4d52677374) static
static const uint64 AdobeXMPCore::kIDOMParserID (0x63444f4d50727372) static
static const uint64 AdobeXMPCore::kIDOMSerializerID (0x63444f4d53726c7a) static
static const uint64 AdobeXMPCore::kIMetadataID (0x634d657461646174) static
static const uint64 AdobeXMPCore::kINameSpacePrefixMapID (0x634e5350724d6170) static
static const uint64 AdobeXMPCore::kINodeID (0x634e6f6465202020) static
Referenced by AdobeXMPCore::INode_v1::ConvertToMetadata().
static const uint64 AdobeXMPCore::kINodeIteratorID (0x634e6f6465497420) static
Referenced by AdobeXMPCore::INodeIterator_v1::Next().
static const uint64 AdobeXMPCore::kIPathID (0x6350617468202020) static
Referenced by AdobeXMPCore::IPath_v1::IsEmpty().
static const uint64 AdobeXMPCore::kIPathSegmentID (0x6350617468536567) static
static const uint64 AdobeXMPCore::kISimpleNodeID (0x63536d6c4e6f6465) static
static const uint64 AdobeXMPCore::kIStructureNodeID (0x635374724e6f6465) static
Referenced by AdobeXMPCore::IStructureNode_v1::GetArrayNode().
XMPToolkit documentation generated by doxygen 1.8.11