#!/usr/bin/env python
# -*- coding: UTF-8 -*-
#
# generated by wxGlade 0.7.1 on Tue Jun 14 17:01:45 2016
#

import wx

# begin wxGlade: dependencies
import gettext
# end wxGlade

# begin wxGlade: extracode
# end wxGlade


class MainFrame(wx.Frame):
    def __init__(self, *args, **kwds):
        # begin wxGlade: MainFrame.__init__
        kwds["style"] = wx.DEFAULT_FRAME_STYLE
        wx.Frame.__init__(self, *args, **kwds)
        self.src_dir_text_ctrl = wx.TextCtrl(self, wx.ID_ANY, "", style=wx.TE_READONLY)
        self.src_dir_button = wx.Button(self, wx.ID_ANY, _("Source folder"))
        self.dest_dir_text_ctrl = wx.TextCtrl(self, wx.ID_ANY, "", style=wx.TE_READONLY)
        self.dst_folder_button = wx.Button(self, wx.ID_ANY, _("Destination folder"))
        self.tiff_checkbox = wx.CheckBox(self, wx.ID_ANY, _("TIFF"))
        self.convert_button = wx.Button(self, wx.ID_ANY, _("Convert"))
        self.status_text_ctrl = wx.TextCtrl(self, wx.ID_ANY, "", style=wx.TE_MULTILINE | wx.TE_READONLY)
        self.abort_button = wx.Button(self, wx.ID_ANY, _("Abort"))

        self.__set_properties()
        self.__do_layout()

        self.Bind(wx.EVT_BUTTON, self.OnSrcFolder, self.src_dir_button)
        self.Bind(wx.EVT_BUTTON, self.OnDstFolder, self.dst_folder_button)
        self.Bind(wx.EVT_BUTTON, self.OnConvert, self.convert_button)
        self.Bind(wx.EVT_BUTTON, self.OnAbort, self.abort_button)
        # end wxGlade

    def __set_properties(self):
        # begin wxGlade: MainFrame.__set_properties
        self.SetTitle(_("SJCAM RAW Converter"))
        self.src_dir_button.SetFocus()
        self.tiff_checkbox.SetToolTip(wx.ToolTip(_("Convert to TIFF as well as DNG")))
        self.abort_button.Enable(False)
        # end wxGlade

    def __do_layout(self):
        # begin wxGlade: MainFrame.__do_layout
        grid_sizer_1 = wx.FlexGridSizer(4, 2, 0, 0)
        grid_sizer_1.Add(self.src_dir_text_ctrl, 0, wx.EXPAND, 0)
        grid_sizer_1.Add(self.src_dir_button, 0, wx.ALIGN_RIGHT | wx.EXPAND, 0)
        grid_sizer_1.Add(self.dest_dir_text_ctrl, 0, wx.EXPAND, 0)
        grid_sizer_1.Add(self.dst_folder_button, 0, wx.ALIGN_RIGHT | wx.EXPAND, 0)
        grid_sizer_1.Add(self.tiff_checkbox, 0, 0, 0)
        grid_sizer_1.Add(self.convert_button, 0, wx.ALL | wx.EXPAND, 2)
        grid_sizer_1.Add(self.status_text_ctrl, 0, wx.EXPAND, 0)
        grid_sizer_1.Add(self.abort_button, 0, wx.EXPAND, 0)
        self.SetSizer(grid_sizer_1)
        grid_sizer_1.Fit(self)
        grid_sizer_1.AddGrowableRow(3)
        grid_sizer_1.AddGrowableCol(0)
        self.Layout()
        # end wxGlade

    def OnSrcFolder(self, event):  # wxGlade: MainFrame.<event_handler>
        dialog = wx.DirDialog(self, "Choose source directory", style=wx.DD_DEFAULT_STYLE | wx.DD_NEW_DIR_BUTTON)
        if dialog.ShowModal() == wx.ID_OK:
            self.src_dir_text_ctrl.SetValue(dialog.GetPath())
        dialog.Destroy()
        event.Skip()

    def OnDstFolder(self, event):  # wxGlade: MainFrame.<event_handler>
        dialog = wx.DirDialog(self, "Choose destination directory", style=wx.DD_DEFAULT_STYLE | wx.DD_NEW_DIR_BUTTON)
        if dialog.ShowModal() == wx.ID_OK:
            self.dest_dir_text_ctrl.SetValue(dialog.GetPath())
        dialog.Destroy()
        event.Skip()

    def OnConvert(self, event):  # wxGlade: MainFrame.<event_handler>
        self.status_text_ctrl.Clear()
        print "Event handler 'OnConvert' not implemented!"
        event.Skip()

    def OnAbort(self, event):  # wxGlade: MainFrame.<event_handler>
        print "Event handler 'OnAbort' not implemented!"
        event.Skip()

# end of class MainFrame
if __name__ == "__main__":
    gettext.install("app") # replace with the appropriate catalog name

    app = wx.PySimpleApp(0)
    main_frame = MainFrame(None, wx.ID_ANY, "")
    app.SetTopWindow(main_frame)
    main_frame.Show()
    app.MainLoop()
